immortalwrt/immortalwrt

package/kernel/kmod-sched-cake-oot/Makefile

In preparation for dropping the out of tree cake module and using
in tree cake from upstream, rename the package to kmod-sched-cake-oot
(out of tree)
Initially add a PROVIDES kmod-sched-cake so that package dependencies
can be satisfied.
Ultimately this package will be removed when linux 4.14 is removed.
Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>

kmod-sched-cake: rename to kmod-sched-cake-oot

---

package/boot/uboot-rockchip/Makefile
package/boot/uboot-rockchip/patches/200-rockchip-rk3399-split-nanopi-r4-rk3399-out-of-evb_rk.patch
package/boot/uboot-rockchip/patches/201-ram-rk3399-Add-support-for-multiple-DDR-types.patch
package/boot/uboot-rockchip/patches/202-arm-dts-rockchip-rename-and-label-gpio-keys-subnodes.patch
package/boot/uboot-rockchip/patches/203-rockchip-rk3399-Add-support-for-FriendlyARM-NanoPi-R.patch
target/linux/rockchip/Makefile
target/linux/rockchip/armv8/base-files/etc/board.d/01_leds
target/linux/rockchip/armv8/base-files/etc/board.d/02_network
target/linux/rockchip/armv8/base-files/etc/hotplug.d/net/40-net-smp-affinity
target/linux/rockchip/image/armv8.mk
target/linux/rockchip/image/nanopi-r4s.bootscript
target/linux/rockchip/patches-5.4/200-arm64-dts-rockchip-rename-and-label-gpio-keys-subnod.patch
target/linux/rockchip/patches-5.4/201-rockchip-rk3399-Add-support-for-FriendlyARM-NanoPi-R.patch

<h2>Hardware</h2>
RockChip RK3399 ARM64 (6 cores)
1GB DDR3 or 4GB LPDDR4 RAM
2x 1000 Base-T
3 LEDs (LAN / WAN / SYS)
1 Button (Reset)
Micro-SD slot
2x USB 3.0 Port
<h2>Installation</h2>
Uncompress the OpenWrt sysupgrade and write it to a micro SD card using
dd.
<h2>Thanks</h2>
@Aes64X - for led lable definitions
@blackfacem  - for testing
@friendlyarm & @mj22226 - for original source code
@jayanta525 - for boot script
@nicksun98 - for special thanks
@quintus-lab - for IRQ settings and testing

rockchip: add support for FriendlyARM NanoPi R4S

---

package/kernel/mac80211/files/lib/wifi/mac80211.sh

An upstream repair caused the wireless to fail to start

mac80211： enable iw_qos_map_set

---

target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit.c

Fix typo in mtdsplit.c

---

package/network/utils/fullconenat/patches/001-fix-init-Repeat-definition.patch

After iptables was updated to 1.8.8, a compilation error occurred during fullconenat compilation due to _init redefinition.

fullconenat: fix _init repeat definition

---

package/network/utils/fullconenat/patches/000-printk.patch

fullconenat-2023-01-01-74c5e6f3/xt_FULLCONENAT.c:1350:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
1350 |   int ret;
|   ^~~

fullconenat：fix compilation warning

---

target/linux/ramips/dts/mt7620a_bolt_bl201.dts
target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
target/linux/ramips/mt7620/base-files/etc/board.d/02_network

1. add bolt_bl201 LED aliases
2. fix bolt_bl201 restart key gpio
3. make bolt_bl201 bootloader read-only
4. add bolt_bl201 partition settings
5. fix bolt_bl201 wrong gpio group
6. update bolt_bl201 LED and network switch settings

Fix bolt bl201 dts and update some device related value

---

package/emortal/autocore/files/cpuinfo

It is possible to display the host machine's temperature on the "Overview" page of OpenWrt running in a virtual machine. However, to enable this feature, additional configuration is required, including setting up SSH keys and providing the host machine's IP address. Therefore, the command actually checks whether the "luci-app-wechatpush" plugin has enabled the feature to retrieve the host machine's temperature. If it is enabled, the command will invoke /usr/share/wechatpush/wechatpush soc to obtain the temperature.

autocore:  Temperature display supports virtual machines.

---

package/emortal/autocore/Makefile

the upstream main has this change: ipq807x: rename target to qualcommax(https://github.com/openwrt/openwrt/pull/12923/commits/f02f6aaa8d4e1025ab4aa9f569123e57f689f4e5) so the ipq807x/generic is renamed to qualcommax/ipq807x, and the tempinfo in autocore get lost
therefore, update filter to re-enable tempinfo on qualcommax/ipq807x

autocore: add targetid qualcommax

---

target/linux/mediatek/dts/mt7981b-jcg-q30-ubootmod.dts
target/linux/mediatek/filogic/base-files/etc/board.d/02_network
target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
target/linux/mediatek/image/filogic.mk

Custom U-Boot source: https://github.com/1715173329/bl-mt798x/tree/extend
Pre-built U-Boot image: https://firmware.download.immortalwrt.eu.org/uboot/mediatek/mt7981-jcg_q30-fip-expand.bin
Factory dts: https://firmware.download.immortalwrt.eu.org/cnsztl/mediatek/filogic/openwrt-mediatek-mt7981-jcg_q30-factory.dts

mediatek: add JCG Q30 (Pro) support

---

package/boot/arm-trusted-firmware-mediatek/Makefile
package/boot/uboot-envtools/files/mediatek_filogic
package/boot/uboot-mediatek/Makefile
package/boot/uboot-mediatek/patches/450-add-cmcc_rax3000m.patch
target/linux/mediatek/dts/mt7981b-cmcc-rax3000m-emmc.dtso
target/linux/mediatek/dts/mt7981b-cmcc-rax3000m-nand-ubootmod.dts
target/linux/mediatek/dts/mt7981b-cmcc-rax3000m-nand.dtso
target/linux/mediatek/dts/mt7981b-cmcc-rax3000m.dts
target/linux/mediatek/filogic/base-files/etc/board.d/02_network
target/linux/mediatek/filogic/base-files/etc/hotplug.d/firmware/11-mt76-caldata
target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
target/linux/mediatek/image/filogic.mk

```
Hardware specification:
SoC: MediaTek MT7981B 2x A53
Flash: 64GB eMMC or 128 MB SPI-NAND
RAM: 512MB
Ethernet: 4x 10/100/1000 Mbps
Switch: MediaTek MT7531AE
WiFi: MediaTek MT7976C
Button: Reset, Mesh
Power: DC 12V 1A
- UART: 3.3v, 115200n8
--------------------------
|         Layout         |
|   -----------------    |
| 4 | GND TX VCC RX | <= |
|   -----------------    |
--------------------------
Gain SSH access:
1. Login into web interface, and download the configuration.
2. Enter fakeroot, decompress the configuration:
tar -zxf cfg_export_config_file.conf
3. Edit 'etc/config/dropbear', set 'enable' to '1'.
4. Edit 'etc/shadow', update (remove) root password:
'root::19523:0:99999:7:::'
5. Repack 'etc' directory:
tar -zcf cfg_export_config_file.conf etc/
* If you find an error about …
```

mediatek: add CMCC RAX3000M support

---

target/linux/rockchip/patches-5.15/804-02-PM-devfreq-event-add-support-for-rk3368-dfi.patch

Fix compilation errors caused by incorrect cherry-pick.

rockchip: refresh patches

---

target/linux/qualcommax/image/ipq807x.mk

Fix variable definition, prevent displaying warnings:
- warning: overriding recipe for target
- warning: ignoring old recipe for target

ipq807x: fix variable definition

---

package/network/config/netifd/files/usr/libexec/network/packet-steering.sh

netifd： Update packet-steering.sh

---

target/linux/ipq40xx/patches-6.6/991-ipq40xx-unlock-cpu-frequency.patch

the qcom-xxx.dtsi has moved to /qcom/ in kernel 6.6, therefore change the patch file path accordingly.
P.S. we'd better double check the line numbers before merge.

ipq40xx: refresh patches

---

target/linux/rockchip/patches-5.15/029-v6.10-arm64-dts-rockchip-Add-cache-information-to-the-SoC-dtsi-.patch

Add missing cache information to the Rockchip RK356x SoC dtsi, to allow
the userspace, which includes lscpu(1) that uses the virtual files provided
by the kernel under the /sys/devices/system/cpu directory, to display the
proper RK3566 and RK3568 cache information.
Adding the cache information to the RK356x SoC dtsi also makes the following
warning message in the kernel log go away:
cacheinfo: Unable to detect cache hierarchy for CPU 0
The cache parameters for the RK356x dtsi were obtained and partially derived
by hand from the cache size and layout specifications found in the following
datasheets and technical reference manuals:
- Rockchip RK3566 datasheet, version 1.1
- Rockchip RK3568 datasheet, version 1.3
- ARM Cortex-A55 revision r1p0 TRM, version 0100-00
- ARM DynamIQ Shared Unit …

[openwrt-23.05] rockchip: Add cache information to the SoC dtsi for RK356x

---

target/linux/ramips/dts/mt7620a_bolt_bl201.dts
target/linux/ramips/image/mt7620.mk
target/linux/ramips/mt7620/base-files/etc/board.d/01_leds

No need to change the bootloader using breedweb anymore.
But breedweb can still be used.
1. Update device baudrate
2. Update some of leds and button gpios values and names
3. Update partition layout to match the stock layout
4. Update missing package depends for usb
5. Add device UIMAGE Magic value

ramips: update Bolt BL201 to match stock bootloader

---

package/boot/uboot-rockchip/src/arch/arm/dts/rk3588-cyber3588-aib.dts
target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts

the last commit https://github.com/immortalwrt/immortalwrt/commit/bff07d91b61cc3e14c91bcfca4076611eae26ad2 introduce error/duplicate_node_names in dts file:
```
arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts:548.33-550.5: ERROR (duplicate_node_names): /pinctrl/gpio-leds/status-led-pin: Duplicate node name
arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts:552.32-554.5: ERROR (duplicate_node_names): /pinctrl/gpio-leds/status-led-pin: Duplicate node name
arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts:552.32-554.5: ERROR (duplicate_node_names): /pinctrl/gpio-leds/status-led-pin: Duplicate node name
ERROR: Input tree has errors, aborting (use -f to force output)
make[8]: *** [scripts/Makefile.lib:423: arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dtb] Error 2
make[7]: *** …
```

rockchip: fix rgb pinctrl duplicate names 

---

package/boot/uboot-envtools/files/mediatek_filogic
target/linux/mediatek/dts/mt7981b-huasifei-wh3000-emmc.dts
target/linux/mediatek/filogic/base-files/etc/board.d/01_leds
target/linux/mediatek/filogic/base-files/etc/board.d/02_network
target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
target/linux/mediatek/image/filogic.mk

The HUASIFEI WH3000 and emmc model ( aka Fudy MT3000) are Wi-Fi 6 5G cellular routers, based on MediaTek MT7981A SoC. 
Specifications:
SoC: Filogic 820 MT7981A (1.3GHz)
RAM: DDR4 1GB
Flash: eMMC 8G
WiFi: 2.4GHz and 5GHz with 3 antennas
Ethernet:
1x WAN (10/100/1000M)
1x LAN (10/100/1000/2500M)
USB: 1x USB 3.0 port
UART:
3.3V, TX, RX, GND / 115200 8N1
Installation via U-Boot rescue:
Connect to the GBE eth port, than press and hold reset button while booting the device
Wait for the Internet led to blink 5 times
Release reset button
The rescue page is accessible via http://192.168.1.1
Select the OpenWrt sysupgrade image and start upgrade
Wait for the router to flash new firmware and reboot

mediatek: filogic: add support for HUASIFEI WH3000 (Fudy MT3000)

---

target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3588-cyber3588-aib.dts
target/linux/rockchip/image/armv8.mk

Fixed property errors in DTS, enabling proper PWM loading. Additionally, added fan control based on package thermal temperature.
test result:
root@ImmortalWrt:/sys/class/thermal/thermal_zone0# echo 45000 > emul_temp
root@ImmortalWrt:/sys/class/thermal/thermal_zone0# cat /sys/class/hwmon/hwmon7/fan1_input
2666
root@ImmortalWrt:/sys/class/thermal/thermal_zone0# echo 55000 > emul_temp
root@ImmortalWrt:/sys/class/thermal/thermal_zone0# cat /sys/class/hwmon/hwmon7/fan1_input
3076
root@ImmortalWrt:/sys/class/thermal/thermal_zone0# echo 75000 > emul_temp
root@ImmortalWrt:/sys/class/thermal/thermal_zone0# cat /sys/class/hwmon/hwmon7/fan1_input
4750

rockchip: fix cyber3588 pwm fan.

---

package/emortal/default-settings/files/99-default-settings

Fixed: condition syntax lost 'fi'

default-settings: fix script syntax

---

target/linux/mediatek/dts/mt7986a-ruijie-rg-x60-pro.dts

Fix the status indicator light of the WAN port.
修复wan口状态灯

mediatek: Ruijie RG-X60 Pro: Fix WAN port status LED

---

target/linux/mediatek/dts/mt7981b-cetron-ct3003.dtsi

dts: fix missing opening brace

mediatek: dts: fix syntax error (mismatched brace '{')

---

package/boot/arm-trusted-firmware-mediatek/Makefile

Other than most boards with DDR3 the TP-Link 7DR7230 v2 cannot use the "comb" DDR calibration option and needs only the "ddr3" option set instead.
Build TF-A to boot with mtk_uartboot for MT7988 with DDR3 RAM.

arm-trusted-firmware-mediatek: add MT7988 BL2 DDR3 RAM image
